-- local RS = game:GetService("ReplicatedStorage")

-- local NeverMorePackages = RS.Nevermore
-- local loader = NeverMorePackages:FindFirstChild("LoaderUtils", true).Parent
-- local Nevermore = require(loader).bootstrapGame(NeverMorePackages)


-- ----------------------------- init process -----------------------------
-- print("_G.ServiceBag ", _G.ServiceBag)

-- ---------- COLDOWNS ----------

-- local Ragdoll = Nevermore("Ragdoll")